name: ci-backend-workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**' # Only trigger when backend files change
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Set Node.js Version
  PYTHON_VERSION: '3.10'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          node-version: ${{env.PYTHON_VERSION}}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pipenv
        run: pip install pipenv
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

      - name: Install dependencies
        run: pipenv install
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

      - name: Run the lint
        run: pipenv run lint
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          node-version: ${{env.PYTHON_VERSION}}

      - name: Cache pipenv virtual environment
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install pipenv
        run: pip install pipenv
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

      - name: Install dependencies
        run: pipenv install
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

      - name: Run tests
        run: pipenv run test
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-python@v3
        with:
          node-version: ${{env.PYTHON_VERSION}}

      - name: Cache pipenv virtual environment
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install pipenv
        run: pip install pipenv
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

      - name: Install dependencies
        run: pipenv install
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/

      - name: Run tests
        run: pipenv run test
        working-directory: /home/runner/work/Project-4-AWS-Final/Project-4-AWS-Final/starter/backend/
